### ISSUE TITLE
Enhancement: show fail sqls in fail blocks

### ISSUE THREAD

**Issue by DQinYuan** [fuzzdebugplatform/fuzz_debug_platform#5]
In "failure rate" tooltip in failure blocks, we can add a link to see failure sqls in the block.

**Comment by DQinYuan** [comment]
I add a new api in back end:

```url
/api/bugsqls?filepath=planner/core/logical_plan_builder.go&startLine=568&endLine=570
```

then you can get bugsqls about this block.

return:

```json
[
"sql1",
"sql2",
"sql3"
]
```

**Comment by baurine** [comment]
Close it because it is done.
